info:
  contact:
    email: david-khala@hotmail.com
  title: go-swagger
  version: v0.0.1
paths:
  /context/{key}:
    get:
      parameters:
      - description: context key
        in: path
        name: key
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
  /panic/{error}:
    get:
      parameters:
      - description: the error message to be replied back in response
        in: path
        name: error
        required: true
        type: string
      responses:
        "500":
          description: Internal Server Error
          schema:
            type: string
  /ping:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
swagger: "2.0"
