name: Github Actions
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  go-cmd:
    env:
      GO111MODULE: "on"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14 # When no go versions are set in workflow file, the default version in GitHub hosted runner is used.
      - run: ./scripts/goCmd.sh get github.com/davidkhala/chaincode
      - name: cleanup
        run: export GOPATH=$(go env GOPATH); rm -rf ${GOPATH}/src/github.com/davidkhala/chaincode/; 
      - run: ./scripts/goCmd.sh get https://github.com/davidkhala/chaincode
      - name: cleanup
        run: export GOPATH=$(go env GOPATH); rm -rf ${GOPATH}/src/github.com/davidkhala/chaincode/; 
      - run: ./scripts/goCmd.sh get https://github.com/davidkhala/chaincode.git
      - name: duplicate test
        run: ./scripts/goCmd.sh get github.com/davidkhala/chaincode
      - name: cleanup
        run: export GOPATH=$(go env GOPATH); rm -rf ${GOPATH}/src/github.com/davidkhala/chaincode/; 
      - run: ./scripts/goCmd.sh get github.com/davidkhala/chaincode release-1.4
