name: Github Actions
on: [push]

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.11
        uses: actions/setup-go@v2
        with:
          go-version: 1.11
        id: go
      - uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          export GO111MODULE=on
          go mod vendor
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .
