name: go-utils
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  checks:
    name: run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: install go
        uses: cedrickring/golang-action/go1.12@1.3.0
        env:
          GO111MODULE: "on"