name: "go module test"
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: check default go version
        run: go version
      - run: go mod vendor
      - run: go test
  extensions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension: [grpc, logger, leveldb]
    defaults:
      run:
        working-directory: ${{matrix.extension}}
    steps:
      - uses: actions/checkout@main
      - run: go mod vendor
      - run: go test
  restful:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restful
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: '^1.20'
      - run: go mod vendor
      - run: go test
      - run: go install github.com/swaggo/swag/cmd/swag@latest
      - run: go generate github.com/davidkhala/goutils/restful/main
  orm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orm
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: '^1.20'
      - uses: ScribeMD/rootless-docker@main
        name: Use Docker in rootless mode.
      - run: docker compose up -d
        working-directory: orm/testdata
      - run: go mod vendor
      - run: go test
